export default {
  login: "/",
  Demo: "/app/Demo",
  RoleChange: "/app/admin/roleChange",
  RequestForm: "/app/EE/RequestForm",
  ProjectInfoCreate: "/app/EE/ProjectInfoCreate",
  Summary: "/app/EE/Summary",
  AllProject: "/app/EE/AllProject",
  ProjectInfo: "/app/EE/ProjectInfo",
  EE: "/app/EE",
  SIV: "/app/SIV",
  SIVPage: {
    TestItem: "/app/SIV/TestItem",
    ProjectInfo: "/app/SIV/ProjectInfo",
    Summary: "/app/SIV/Summary",
    AllProject: "/app/SIV/AllProject",
    MemberSetting: "/app/SIV/MemberSetting",
  },
  Power: "/app/Power",
  PowerPage: {
    TestItem: "/app/Power/TestItem",
    ProjectInfo: "/app/Power/ProjectInfo",
    Summary: "/app/Power/Summary",
    AllProject: "/app/Power/AllProject",
    MemberSetting: "/app/Power/MemberSetting",
  },
  EMC: "/app/EMC",
  EMCPage: {
    TestItem: "/app/EMC/TestItem",
    ProjectInfo: "/app/EMC/ProjectInfo",
    Summary: "/app/EMC/Summary",
    AllProject: "/app/EMC/AllProject",
    MemberSetting: "/app/EMC/MemberSetting",
  },
  RF: "/app/RF",
  RFPage: {
    TestItem: "/app/RF/TestItem",
    ProjectInfo: "/app/RF/ProjectInfo",
    Summary: "/app/RF/Summary",
    AllProject: "/app/RF/AllProject",
    MemberSetting: "/app/RF/MemberSetting",
  },
  ListUser: "/app/ListUser",
  DataPipeline: "/app/pipeline",
  DataPipelinePage: {
    CreatePipeline: "/app/pipeline/create",
    TablePermission: "/app/pipeline/permission",
    Workspace: "/app/pipeline/workspace",
  },
  Group: "/app/group",
  GroupPage: {
    Management: "/app/group/management",
    Permission: "/app/group/permission",
  }
};
